baseURL = "https://www.howie6879.cn/"
title = "è€èƒ¡çš„å‚¨ç‰©æŸœ"
theme = "maupassant"
googleAnalytics = ""                  # UA-XXXXXXXX-X

## ä¿æŒåˆ†ç±»çš„åŸå§‹åå­—ï¼ˆfalseä¼šåšè½¬å°å†™å¤„ç†ï¼‰
preserveTaxonomyNames = false
## æ˜¯å¦ç¦æ­¢URL Pathè½¬å°å†™
disablePathToLower = false
hasCJKLanguage = true
summaryLength = 140

# disqusShortname = "yourdiscussshortname"  ## æ˜¯å¦å¼€å¯disqusè¯„è®ºï¼Œä¸è¦å’ŒutterancåŒæ—¶å¼€å¯

[author]
name = "howie.hu"

[params]
author = "howie6879"
subtitle = "ç¼–ç¨‹ã€å…´è¶£ã€ç”Ÿæ´»"
keywords = "python,rust,æœºå™¨å­¦ä¹ ,æ¸¸æˆé£æ§,sanic,é¡¹ç›®ç®¡ç†,æ·±åº¦å­¦ä¹ ,å…¬ä¼—å·,å°ç¨‹åº"
description = "å¥‡æ–‡å…±æ¬£èµï¼Œç–‘ä¹‰ç›¸ä¸æ"
# å…¨å±€å¼€å…³ï¼Œä½ ä¹Ÿå¯ä»¥åœ¨æ¯ä¸€ç¯‡å†…å®¹çš„ front matter ä¸­é’ˆå¯¹å•ç¯‡å†…å®¹å…³é—­æˆ–å¼€å¯æŸäº›åŠŸèƒ½
toc = true         # æ˜¯å¦å¼€å¯ç›®å½•
busuanzi = true    #å¯ç”¨ä¸ç®—å­ç½‘é¡µç»Ÿè®¡
googleAd = ""      #ca-pub-xxxxxxxxxxxxxx
localSearch = true # å¯ç”¨æœ¬åœ°æœç´¢

# customCSS = ['heti.min.css']
# if ['custom.css'], load '/static/css/custom.css' file
#   customJS = ['douban.js']
# if ['custom.js'], load '/static/js/custom.js' file

## å‹æƒ…é“¾æ¥ï¼Œå¯ä»¥å¤šä¸ª

[[params.links]]
title = "elfgzp"
name = "elfgzp"
url = "https://elfgzp.cn/"

[[params.links]]
title = "Ruter"
name = "Ruter"
url = "https://ruterly.com/"

[[params.links]]
title = "shidenggui"
name = "shidenggui"
url = "https://shidenggui.com/"

[[params.links]]
title = "Bensz"
name = "Bensz"
url = "https://blognas.hwb0307.com/"

## ä¾§è¾¹æ å¹¿å‘Šä½
# [[params.ads]]
# title = "ã€2019åŒ12ã€‘ALL IN CLoud ä½è‡³1æŠ˜"
# url = "https://www.aliyun.com/minisite/goods?userCode=jdg9oj97&share_source=copy_link"
# img = "https://img.alicdn.com/tfs/TB1_rYHo7P2gK0jSZPxXXacQpXa-690-388.jpg"

## ä¸ªäººä¸“æ 
[[params.special_column]]
title = "ğŸ‘€ æˆ‘çš„å‘¨åˆŠ"
url = "https://weekly.howie6879.cn/"

[[params.special_column]]
title = "ğŸ•¸ k8så­¦ä¹ ä¹‹è·¯"
url = "https://www.howie6879.cn/k8s/"
# img = "https://img.alicdn.com/tfs/TB1_rYHo7P2gK0jSZPxXXacQpXa-690-388.jpg"

[[params.special_column]]
title = "ğŸ¤– æœºå™¨å­¦ä¹ æ–‡é›†"
url = "https://www.howie6879.cn/ml_book/"

[[params.special_column]]
title = "ğŸ‘¾ Sanic-For-Pythoneer"
url = "https://www.howie6879.cn/sanic_book/"

## é…ç½® utterancè¯„è®º,æ•™ç¨‹å‚è€ƒ https://utteranc.es/
# [params.utteranc]
# enable = true
# repo = "howie6879.github.io" ##æ¢æˆè‡ªå·±çš„
# issueTerm = "pathname"
# theme = "github-light"

## å¼€å¯ç‰ˆæƒå£°æ˜ï¼Œåè®®åå­—å’Œé“¾æ¥éƒ½å¯ä»¥æ¢
[params.cc]
name = "çŸ¥è¯†å…±äº«ç½²å-éå•†ä¸šæ€§ä½¿ç”¨-ç¦æ­¢æ¼”ç» 4.0 å›½é™…è®¸å¯åè®®"
link = "https://creativecommons.org/licenses/by-nc-nd/4.0/"

## é…ç½®ä»£ç é«˜äº®
[markup]
[markup.highlight]
lineNos = true
style = "github"

## é…ç½®ç½‘ç«™èœå•

[menu]

[[menu.main]]
identifier = "archives"
name = "å½’æ¡£"
url = "/page/archives/"
weight = 2

# [[menu.main]]
# identifier = "book"
# name = "æ–‡é›†"
# url = "/page/book/"
# weight = 3

[[menu.main]]
identifier = "about"
name = "å…³äº"
url = "/about/"
weight = 3
